services:
  - type: web
    name: messenger-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js   # or whatever your entry file is
    envVars:
      - key: VERIFY_TOKEN
        sync: false
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
