services:
  - type: web
    name: messenger-bot
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start   # or whatever your entry file is
    envVars:
      - key: VERIFY_TOKEN
        sync: false
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
